name: "Terraform Validate"

on:
  pull_request:

jobs:
  terraform:
    name: "Terraform Validate"
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Setup Terraform with specified version on the runner
        uses: hashicorp/setup-terraform@v2

      - name: Terraform init (AWS EC2)
        working-directory: ./aws-ec2
        run: terraform init

      - name: Terraform format (AWS EC2)
        working-directory: ./aws-ec2
        run: terraform fmt

      - name: Terraform validate (AWS EC2)
        working-directory: ./aws-ec2
        run: terraform validate
    

    