name: "Terraform Validate"

on:
  pull_request:

jobs:
  terraform:
    name: "Terraform Validate"
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Setup Terraform (AWS)
        run: cd aws-ec2 && terraform plan -no-color

    